// <auto-generated />
using System;
using AuctionHouse.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuctionHouse.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220330131730_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuctionHouse.Domain.Auction.Auction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("auction_ends");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Version"));

                    b.HasKey("Id");

                    b.ToTable("auction", (string)null);
                });

            modelBuilder.Entity("AuctionHouse.Domain.BidHistory.Bid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid")
                        .HasColumnName("auction_id");

                    b.Property<Guid>("Bidder")
                        .HasColumnType("uuid")
                        .HasColumnName("bidder_id");

                    b.Property<DateTimeOffset>("TimeOfBid")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_of_bid");

                    b.HasKey("Id");

                    b.ToTable("bid_history", (string)null);
                });

            modelBuilder.Entity("AuctionHouse.Domain.Auction.Auction", b =>
                {
                    b.OwnsOne("AuctionHouse.Domain.Auction.Money", "StartingPrice", b1 =>
                        {
                            b1.Property<Guid>("AuctionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("starting_price");

                            b1.HasKey("AuctionId");

                            b1.ToTable("auction");

                            b1.WithOwner()
                                .HasForeignKey("AuctionId");
                        });

                    b.OwnsOne("AuctionHouse.Domain.Auction.WinningBid", "WinningBid", b1 =>
                        {
                            b1.Property<Guid>("AuctionId")
                                .HasColumnType("uuid")
                                .HasColumnName("auction_id");

                            b1.Property<Guid>("Bidder")
                                .HasColumnType("uuid")
                                .HasColumnName("bidder_member_id");

                            b1.Property<DateTimeOffset>("TimeOfBid")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("time_of_bid");

                            b1.HasKey("AuctionId");

                            b1.ToTable("winning_bid", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AuctionId");

                            b1.OwnsOne("AuctionHouse.Domain.Auction.Price", "CurrentAuctionPrice", b2 =>
                                {
                                    b2.Property<Guid>("WinningBidAuctionId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("WinningBidAuctionId");

                                    b2.ToTable("winning_bid");

                                    b2.WithOwner()
                                        .HasForeignKey("WinningBidAuctionId");

                                    b2.OwnsOne("AuctionHouse.Domain.Auction.Money", "Amount", b3 =>
                                        {
                                            b3.Property<Guid>("PriceWinningBidAuctionId")
                                                .HasColumnType("uuid");

                                            b3.Property<decimal>("Value")
                                                .HasColumnType("numeric")
                                                .HasColumnName("current_price");

                                            b3.HasKey("PriceWinningBidAuctionId");

                                            b3.ToTable("winning_bid");

                                            b3.WithOwner()
                                                .HasForeignKey("PriceWinningBidAuctionId");
                                        });

                                    b2.Navigation("Amount")
                                        .IsRequired();
                                });

                            b1.OwnsOne("AuctionHouse.Domain.Auction.Money", "MaximumBid", b2 =>
                                {
                                    b2.Property<Guid>("WinningBidAuctionId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Value")
                                        .HasColumnType("numeric")
                                        .HasColumnName("maximum_bid");

                                    b2.HasKey("WinningBidAuctionId");

                                    b2.ToTable("winning_bid");

                                    b2.WithOwner()
                                        .HasForeignKey("WinningBidAuctionId");
                                });

                            b1.Navigation("CurrentAuctionPrice")
                                .IsRequired();

                            b1.Navigation("MaximumBid")
                                .IsRequired();
                        });

                    b.Navigation("StartingPrice")
                        .IsRequired();

                    b.Navigation("WinningBid");
                });

            modelBuilder.Entity("AuctionHouse.Domain.BidHistory.Bid", b =>
                {
                    b.OwnsOne("AuctionHouse.Domain.Auction.Money", "AmountBid", b1 =>
                        {
                            b1.Property<Guid>("BidId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("bid");

                            b1.HasKey("BidId");

                            b1.ToTable("bid_history");

                            b1.WithOwner()
                                .HasForeignKey("BidId");
                        });

                    b.Navigation("AmountBid")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
